name: swinir
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2025.11.4=haa95532_0
  - certifi=2024.8.30=py38haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cccl=13.0.85=h5221881_1
  - cuda-cccl_win-64=13.0.85=hc667259_1
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.85=h17533db_0
  - cuda-opencl-dev=13.0.85=hde976d8_0
  - cuda-profiler-api=13.0.85=h5221881_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - filelock=3.13.1=py38haa95532_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmpy2=2.1.2=py38h7f96b67_0
  - idna=3.7=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.4=py38haa95532_0
  - jpeg=9f=ha349fce_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.0.35=h86a452a_1
  - libcurand-dev=10.4.0.35=hde976d8_1
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py38h2bbff1b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py38haa95532_0
  - networkx=3.1=py38haa95532_0
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - opencl-headers=2025.07.22=h885b0b7_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - pillow=10.4.0=py38h827c3e9_0
  - pip=24.2=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.20=h8205438_0
  - pytorch=2.4.1=py3.8_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py38h827c3e9_0
  - requests=2.32.3=py38haa95532_0
  - setuptools=75.1.0=py38haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - sympy=1.13.3=py38haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - typing_extensions=4.11.0=py38haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.2.3=py38haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - einops==0.8.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - h5py==3.11.0
      - hdf5storage==0.1.19
      - huggingface-hub==0.36.0
      - imageio==2.35.1
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lmdb==1.7.5
      - matplotlib==3.7.5
      - ninja==1.13.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pywavelets==1.4.1
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scipy==1.10.1
      - six==1.17.0
      - tifffile==2023.7.10
      - timm==1.0.22
      - torchaudio==2.4.1
      - torchvision==0.20.0
      - tqdm==4.67.1
      - zipp==3.20.2
prefix: C:\Users\user\miniconda3\envs\swinir
